<?php

namespace App;


use App\Scopes\BuyerScope;
use App\Transformers\BuyerTransfomer;

class Buyer extends User
{

    public $transformer = BuyerTransfomer::class;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(new BuyerScope());
    }

    public function transactions()
    {
        return $this->hasMany(Transaction::class);
    }
}
