<?php

namespace App;


use App\Scopes\SellerScope;
use App\Transformers\SellerTransfomer;

class Seller extends User
{

    public $transformer = SellerTransfomer::class;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(new SellerScope());
    }

    public function products()
    {
        return $this->hasMany(Product::class);
    }
}
